services:
  - type: web
    name: movie-recommend-system
    runtime: python3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run main.py --server.port=$PORT --server.address=0.0.0.0"
